// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbqxttacfibpfjfijvyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdicXh0dGFjZmlicGZqZmlqdnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MTQxMDksImV4cCI6MjA1Mzk5MDEwOX0.TKU_yYyQn4RvnRjcIaXOUpp1nTN_ZSmvx9UZ8V_XTrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);